# Generated by Django 3.2.5 on 2021-07-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.FileField(blank=True, max_length=254, null=True, upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Simple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GenderFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('KaggleMotivationFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('CurrentJobTitleFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('MLToolNextYearFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('MLMethodNextYearFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('LanguageRecommendationFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('PublicDatasetsFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('PersonalProjectsChallengeFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('LearningPlatformCommunityFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('LearningPlatformFreeForm1', models.CharField(blank=True, max_length=500, null=True)),
                ('LearningPlatformFreeForm2', models.CharField(blank=True, max_length=500, null=True)),
                ('LearningPlatformFreeForm3', models.CharField(blank=True, max_length=500, null=True)),
                ('LearningPlatformUsefulnessCommunitiesFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('LearningPlatformUsefulnessFreeForm1Select', models.CharField(blank=True, max_length=500, null=True)),
                ('LearningPlatformUsefulnessFreeForm1SelectFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('LearningPlatformUsefulnessFreeForm2Select', models.CharField(blank=True, max_length=500, null=True)),
                ('LearningPlatformUsefulnessFreeForm2SelectFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('LearningPlatformUsefulnessFreeForm3Select', models.CharField(blank=True, max_length=500, null=True)),
                ('LearningPlatformUsefulnessFreeForm3SelectFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('BlogsPodcastsNewslettersFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('JobSkillImportanceOtherSelect1FreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('JobSkillImportanceOtherSelect2FreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('JobSkillImportanceOtherSelect3FreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('CoursePlatformFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('HardwarePersonalProjectsFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('ProveKnowledgeFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('ImpactfulAlgorithmFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('InterestingProblemFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('DataScienceIdentityFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('MajorFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('PastJobTitlesFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('FirstTrainingFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('LearningCategoryOtherFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('MLSkillsFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('MLTechniquesFreeform', models.CharField(blank=True, max_length=500, null=True)),
                ('EmployerIndustryOtherFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('EmployerSearchMethodOtherFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('JobFunctionFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkHardwareFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkDataTypeFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkLibrariesFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkAlgorithmsFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkToolsFreeForm1', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkToolsFreeForm2', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkToolsFreeForm3', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkToolsFrequencySelect1FreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkFrequencySelect2FreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkFrequencySelect3FreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkMethodsFreeForm1', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkMethodsFreeForm2', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkMethodsFreeForm3', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkMethodsFrequencySelect1FreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkMethodsFrequencySelect2FreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkMethodsFrequencySelect3FreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('TimeOtherSelectFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkChallengesFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkChallengeFrequencyOtherFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkMLTeamSeatFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkDataStorageFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkCodeSharingFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('SalaryChangeFreeForm', models.CharField(blank=True, max_length=500, null=True)),
                ('JobSearchResourceFreeForm', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
