# Generated by Django 3.2.5 on 2021-07-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
